name: Deploy to GitHub Pages (develop)

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # プロジェクトに合わせてNode.jsのバージョンを指定

    - name: Install Dependencies
      run: npm install # または pnpm install

    - name: Build
      run: npm run build # または pnpm run build

    - name: Create gh-pages branch if it doesn't exist
    run: |
      if ! git ls-remote --heads origin gh-pages; then
        git checkout --orphan gh-pages
        git reset --hard
        git commit --allow-empty -m "Initial gh-pages commit"
        git push origin gh-pages
      else
        git checkout gh-pages
      fi

    - name: Deploy to /dev directory
      run: |
        git checkout gh-pages
        mkdir -p dev
        cp -r dist/* dev/
        git add dev
        git commit -m "Deploy develop branch to /dev directory"
        git push origin gh-pages